//! End-to-end test of the generator, from a vendored fixture JLL all the
//! way to the generated files on disk. This never touches the network:
//! `tests/fixtures/example_jll` is a small hand-written stand-in for a real
//! JLL repository, read through the same `Source` a `--url` local path
//! would use.

use std::fs;

use meson_jll::generate;
use meson_jll::jll;
use meson_jll::source::CustomSource;
use meson_jll::Error;

fn fixture_source() -> CustomSource {
    let fixture_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/example_jll");
    CustomSource::parse(fixture_dir, "unused")
}

#[test]
fn generates_a_full_wrap_set_from_a_fixture_jll() {
    let source = fixture_source();
    let package = jll::load(&source).expect("fixture metadata should parse");

    assert_eq!(package.name, "ExampleThing");
    assert_eq!(package.version, "1.2.3+0");
    assert_eq!(package.platforms.len(), 2);
    assert!(package.dependencies.is_empty());

    let output_dir = tempfile::tempdir().expect("could not create a temp dir");
    generate::write_wrap_set(&package, output_dir.path(), false)
        .expect("generation should succeed");

    let selector_wrap = fs::read_to_string(output_dir.path().join("ExampleThing.wrap")).unwrap();
    // Every generated file leads with the exact meson-jll version that
    // wrote it, useful when a bug report includes the file but not the
    // tool version.
    assert!(selector_wrap.contains(&format!(
        "# Generated by meson-jll v{}",
        env!("CARGO_PKG_VERSION")
    )));
    assert!(selector_wrap.contains("# meson-jll: name=ExampleThing version=1.2.3+0"));
    assert!(selector_wrap.contains("directory = ExampleThing"));
    assert!(selector_wrap.contains("dependency_names = ExampleThing_jll"));
    // Meson does not discover packagefiles/<name>/ on its own: without this,
    // the overlay is silently never applied.
    assert!(selector_wrap.contains("patch_directory = ExampleThing"));
    // A source-less [wrap-file] is rejected by Meson outright: it always
    // requires a source_filename, even for an overlay-only wrap.
    assert!(selector_wrap.contains(&format!(
        "source_filename = {}",
        generate::EMPTY_TAR_FILENAME
    )));
    assert!(output_dir
        .path()
        .join("packagefiles")
        .join(generate::EMPTY_TAR_FILENAME)
        .exists());

    let selector_overlay = fs::read_to_string(
        output_dir
            .path()
            .join("packagefiles/ExampleThing/meson.build"),
    )
    .unwrap();
    assert!(selector_overlay.contains(
        "host_machine.cpu_family() == 'x86_64' and host_machine.system() == 'linux' and libc == 'gnu'"
    ));
    assert!(selector_overlay
        .contains("host_machine.cpu_family() == 'aarch64' and host_machine.system() == 'darwin'"));
    assert!(selector_overlay.contains("subproject('ExampleThing-' + triplet)"));
    assert!(selector_overlay
        .contains("meson.override_dependency('ExampleThing_jll', examplething_dep)"));

    let linux_wrap =
        fs::read_to_string(output_dir.path().join("ExampleThing-x86_64-linux-gnu.wrap")).unwrap();
    assert!(linux_wrap.contains(
        "source_url = https://example.invalid/ExampleThing.v1.2.3.x86_64-linux-gnu.tar.gz"
    ));
    assert!(linux_wrap.contains(
        "source_hash = 1111111111111111111111111111111111111111111111111111111111111111"
    ));
    assert!(linux_wrap.contains("patch_directory = ExampleThing-x86_64-linux-gnu"));

    let linux_overlay = fs::read_to_string(
        output_dir
            .path()
            .join("packagefiles/ExampleThing-x86_64-linux-gnu/meson.build"),
    )
    .unwrap();
    // find_library() is defensive: required: false plus a link_args fallback
    // straight at the exact file the wrapper script names, since not every
    // JLL product ships a plain, unversioned, linkable name in lib/ (see
    // CompilerSupportLibraries_jll's libgcc_s on macOS and libssp on Windows).
    assert!(linux_overlay.contains(
        "libexample = cc.find_library('example', dirs: meson.current_source_dir() / 'lib', required: false)"
    ));
    assert!(linux_overlay.contains("if not libexample.found()"));
    assert!(linux_overlay.contains(
        "libexample = declare_dependency(link_args: [meson.current_source_dir() / 'lib/libexample.so'])"
    ));
    assert!(linux_overlay.contains("examplething_dep = declare_dependency("));

    // Regression test: a product whose tarball ships only a versioned
    // soname, no unversioned dev symlink (macOS libgcc_s in
    // CompilerSupportLibraries_jll is the real case this covers). The
    // fallback must link straight against the exact versioned path the
    // wrapper script names, not a reconstructed plain `lib<name>.dylib`
    // find_library() would have looked for.
    let darwin_overlay = fs::read_to_string(
        output_dir
            .path()
            .join("packagefiles/ExampleThing-aarch64-darwin/meson.build"),
    )
    .unwrap();
    assert!(darwin_overlay.contains(
        "libversioned = cc.find_library('versioned', dirs: meson.current_source_dir() / 'lib', required: false)"
    ));
    assert!(darwin_overlay.contains("if not libversioned.found()"));
    assert!(darwin_overlay.contains(
        "libversioned = declare_dependency(link_args: [meson.current_source_dir() / 'lib/libversioned.1.1.dylib'])"
    ));
    // The template's own explanatory comments (Jinja `{# #}` comments) are
    // for maintainers reading the .jinja source, not for the generated
    // output: this one, on why the whole runtime directory is installed,
    // should never appear in the generated meson.build.
    assert!(!linux_overlay.contains("A JLL tarball also ships"));
    // The declared dependency carries the JLL's full release version so a
    // consumer can pin it.
    assert!(linux_overlay.contains("version: '1.2.3+0'"));
    // Only what a declared product actually needs is installed, worked out
    // at configure time by prune_unused_libs.py against the extracted
    // tarball. A JLL ships a good deal a consumer never loads: the GCC
    // sanitizer runtimes in CompilerSupportLibraries alone were ~90MB of
    // one real wheel.
    assert!(linux_overlay.contains("prune_unused_libs"));
    assert!(linux_overlay.contains("install_data(install_libs, install_dir: get_option('libdir'))"));
    // The whole runtime directory is still installed when nothing could be
    // pruned (no python3, no inspection tool, an unparseable binary), since
    // shipping too much is only wasteful while shipping too little is
    // broken.
    assert!(linux_overlay.contains("install_subdir("));
    assert!(linux_overlay.contains("exclude_directories: ['cmake', 'pkgconfig', 'gcc']"));
    // The script itself is written once, next to the other shared scripts,
    // rather than copied into every triplet overlay.
    assert!(output_dir
        .path()
        .join("packagefiles/prune_unused_libs.py")
        .exists());
    // Stripping is gated on -Dstrip and a strip tool being found, and (since
    // meson-python's wheel builder never sees an add_install_script) is a
    // real build-time custom_target per declared product, not a post-install
    // script. It goes through strip_or_copy.py, which falls back to a plain
    // copy if the strip tool cannot parse the particular binary, rather than
    // failing the whole build over a library that would just ship unstripped
    // anyway.
    assert!(linux_overlay
        .contains("should_strip = get_option('strip') and python3.found() and strip_tool.found()"));
    assert!(linux_overlay.contains("'example-stripped'"));
    assert!(linux_overlay.contains(
        "command: [python3, strip_or_copy, strip_tool.full_path(), '@INPUT@', '@OUTPUT@']"
    ));
    // The fallback's bulk directory install excludes each declared
    // product's own file only once stripping is actually active, so the
    // unstripped file is never present alongside its stripped
    // custom_target replacement.
    assert!(linux_overlay.contains("exclude_files: stripped_separately"));
    assert!(linux_overlay.contains("stripped_separately = should_strip ? ['libexample.so'"));
    // On the pruned path every reachable library is stripped, not only the
    // declared products, since the set is known by name at that point.
    assert!(linux_overlay.contains("name + '-stripped'"));

    // This fixture never splits a platform by ABI, so no options file.
    assert!(!output_dir
        .path()
        .join("packagefiles/ExampleThing/meson.options")
        .exists());

    let error = generate::write_wrap_set(&package, output_dir.path(), false).unwrap_err();
    assert!(matches!(error, Error::AlreadyExists { .. }));

    generate::write_wrap_set(&package, output_dir.path(), true)
        .expect("forced regeneration should succeed");
}
